### ISSUE TITLE
Error Listen EADDRINUSE: address already in use :::19000

### ISSUE THREAD

**Issue by thenotoriousjr** [AlexMachin1997/Shopping-List-Assistant-With-Expo#15]
`Starting project at /Users/pikachu06/Desktop/native/Shopping-List-Assistant-With-Expo
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
error listen EADDRINUSE: address already in use :::19000. 

Error: listen EADDRINUSE: address already in use :::19000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at /Users/pikachu06/Desktop/native/Shopping-List-Assistant-With-Expo/node_modules/metro/src/index.js:257:20
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/pikachu06/Desktop/native/Shopping-List-Assistant-With-Expo/node_modules/metro/src/index.js:256:14)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pikachu06/Desktop/native/Shopping-List-Assistant-With-Expo/node_modules/metro/src/index.js:46:24)
    at _next (/Users/pikachu06/Desktop/native/Shopping-List-Assistant-With-Expo/node_modules/metro/src/index.js:66:9)
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (/Users/pikachu06/.config/yarn/global/node_modules/xdl/src/start/startLegacyReactNativeServerAsync.ts:271:16)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)`

I have nothing running in my node. Any idea? This when is I run expo start. Thanks.

**Comment by AlexMachin1997** [comment]
This app is no longer actively maintained.

It's using an outdated version of Expo, they are on something like version 42 while this is still on version 37ish.

I wish I had the time to work on this app, but on Weekends I just want to not code after coding all week.
